---
services:
  redis:
    image: redis:latest
    pull_policy: missing
    restart: unless-stopped
    hostname: "redis.caspersbox.local"
    container_name: "redis"
    networks:
      service-network:
        ipv4_address: 192.168.1.30
    ports:
      - 6379:6379
    env_file:
      - path: ./.env
        required: true
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0"]
    volumes:
      - redis-data:/data:rw
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

---
volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/redis/data"

---
networks:
  service-network:
    external: true
