---
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: missing
    restart: unless-stopped
    hostname: mssql.fedora.local
    container_name: mssql
    networks:
      service-network:
        ipv4_address: 192.168.1.20
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD_FILE: /run/secrets/mssql
      MSSQL_SA_PASSWORD_FILE: /run/secrets/mssql
      MSSQL_PID: "Developer"
    secrets:
      - source: mssql
        target: /run/secrets/mssql
    volumes:
      - mssql-data:/var/opt/mssql:rw
      - mssql-passwd:/tmp/mssql:ro
    healthcheck:
      # test: ["CMD", "nc", "-vz", "localhost", "1433"]
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "$(cat /run/secrets/mssql)", "-C", "-Q", "SELECT @@VERSION"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

---
volumes:
  mssql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/mssql/data"

  mssql-passwd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "~/workspace/mssql/mssql.txt"

---
networks:
  service-network:
    external: true

---
secrets:
  mssql:
    file: "~/workspace/mssql/mssql.txt"
