---
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: missing
    hostname: mssql
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD_FILE: "/run/secrets/mssql"
      MSSQL_SA_PASSWORD_FILE: "/run/secrets/mssql'
      MSSQL_PID: "Developer" 
    networks:
      service-network:
        ipv4_address: 192.168.1.12
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YBfRyAW9j7SC3Auduzz0q74COaV5ooV9", "-C", "-Q", "SELECT @@VERSION"]
      interval: 30s
      timeout: 10s
      retries: 5

---
volumes:
  mssql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/mssql/data"

---
networks:
  service-network:
    external: true

---
secrets:
  mssql:
    file: "~/workspace/mssql/mssql.txt"
