---
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: missing
    restart: unless-stopped
    hostname: "mssql.caspersbox.local"
    container_name: "mssql"
    networks:
      service-network:
        ipv4_address: 192.168.1.20
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD_FILE: /run/secrets/mssql
      MSSQL_SA_PASSWORD_FILE: /run/secrets/mssql
      MSSQL_PID: "Developer"
    secrets:
      - source: mssql
        target: /run/secrets/mssql
    volumes:
      - mssql-data:/var/opt/mssql:rw

---
volumes:
  mssql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/mssql/data"

---
networks:
  service-network:
    external: true

---
secrets:
  mssql:
    file: "~/workspace/mssql/mssql.txt"
