---
apiVersion: v1
kind: Secret
metadata:
  name: store-file-secret
type: Opaque
data:
  keystore.p12: << base64 file data >>
  truststore.p12: << base64 file data >>

---
apiVersion: v1
kind: Secret
metadata:
  name: store-password-secret
type: Opaque
stringData:
  keystore-password: "changeit"
  truststore-password: "changeit"
