---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local"
  hostPath: "/opt/kubernetes/data"

kind: PersistentVolumeClaim
metadata:
  name: default-pvclaim
  namespace: "namespace"
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5gi
  volumeName: "default-pv"
