---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs"
  nfs:
    server: 192.168.12.6
    path: "/appdata"
  mountOptions:
    - proto=tcp
    - nfsvers=4
    - soft
    - noatime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "test-pvclaim"
  namespace: "namespace"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: test-pv
