---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "test-pv"
  namespace: "<< namespace >>"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs"
  nfs:
    server: nfs-service.storage.svc.cluster.local
    path: "/exports"
  mountOptions:
    - proto=tcp
    - nfsvers=4
    - soft
    - noatime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "test-pvclaim"
  namespace: "<< namespace >>"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: test-pv
