---
services:
  kafka:
    image: apache/kafka:4.1.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: "fzR8_urgTSCZgFdIBSwJOg"
      KAFKA_KRAFT_MODE: "true"
      KAFKA_CLUSTER_ID: "fzR8_urgTSCZgFdIBSwJOg"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_LISTENER_NAMES: "CONTROLLER"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  kafka_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/khuntly/workspace/Apache/kafka/kafka_data"
