# ====  ANSIBLE   =============================================================
#          NAME:  group_vars/all/main.yml
#   DESCRIPTION:  Common variables that apply to this play
# =============================================================================
---
install:
  base_path: "{{ ansible_user_dir }}/.dotfiles"

user_account:
  name:
  email:
  home_dir:
  ssh:
    generate_keys:
    fetch_keys:
    key_type:
    passphrase:
  gpg:
    generate_keys:
    fetch_keys:
    passphrase:
