# ====  ANSIBLE   =============================================================
#          NAME:  group_vars/all/main.yml
#   DESCRIPTION:  Common variables that apply to this play
# =============================================================================
---
install:
  base_path: "{{ ansible_user_dir }}/.dotfiles"

secrets:
  BW_ACCESS_TOKEN: ""
  GCP_ACCESS_TOKEN: ""

user_account:
  name: ""
  email: ""
  home_dir: "{{ ansible_user_dir }}"
  setup_ansible: false
  ssh:
    generate_keys: false
    fetch_keys: false
    key_type: ""
    passphrase: ""
  gpg:
    generate_keys: false
    fetch_keys: false
    passphrase: ""
    signing_key: ""
  systemd:
    enabled: false
    enabled_services:
      - ""
