# ====  ANSIBLE   =================================================
#        NAME:  roles/dotfiles/vars/main.yml
# DESCRIPTION:  Template variables for dotfiles
#        NOTE: This file is meant to be a template and saved as ${G
# =================================================================
---
# secrets:
#   google:
#     GCP_SERVICE_ACCOUNT: ""
#
# gcp:
#   projects:
#     project_id: ""
#
# user_account:
#   name: ""
#   email: ""
#
#   ssh:
#     enabled: <true | false>
#     fetch_keys: <true | false>
#     key_source: ""
#     key_id: ""
#     generate_keys: <true | false>
#     passphrase: ""
#     key_type: "<< KEY_TYPE>>"
#     key_data: |
#       << Paste key data here >>
#
#   gpg:
#     enabled: <true | false>
#     fetch_keys: <true | false>
#     key_source: ""
#     key_id: ""
#     generate_keys: <true | false>
#     key_type: ""
#     key_length: 0
#     subkey_type: ""
#     subkey_length: 0
#     expiry: ""
#     passphrase: ""
#     key_data: |
#       << Paste key data here >>
#
#   git:
#     enabled: <true | false>
#     fetch_keys: <true | false>
#     key_source: ""
#     key_id: ""
#     signing_key: ""
#     key_name: ""
#     key_data: |
#       << Paste key data here >>
#
#   smtp:
#     accounts:
#       - name: ""
#         enabled: <true | false>
#         account_name: ""
#         username: ""
#         password: ""
#         hostname: ""
#         port: 
#         use_tls: <true | false>
#
#   systemd:
#     enabled: <true | false>
#     services:
#       - name: ""
