# ====  ANSIBLE   =============================================================
#          NAME:  roles/dotfiles/vars/main.yml
#   DESCRIPTION:  Template variables for dotfiles
#          NOTE: This file is meant to be a template and saved as ${GIT_CLONE_DIR}/ansible/vault/dotfiles.yml as an ansible vault
# =============================================================================
---
# secrets:
#   bitwarden:
#     BW_ACCESS_TOKEN: ""
#
#   google:
#     GCP_SERVICE_ACCOUNT: ""
#
# gcp:
#   projects:
#     project_id: ""
#
# user_account:
#   name: ""
#   email: ""
#
#   ssh:
#     enabled: < true | false >
#     fetch_keys: < true | false >
#     key_source: ""
#     key_id: ""
#     generate_keys: < true | false >
#     passphrase: ""
#     key_type: ""
#
#   gpg:
#     enabled: < true | false >
#     fetch_keys: < true | false >
#     key_source: ""
#     key_id: ""
#     generate_keys: < true | false >
#     key_type: ""
#     key_length: < length >
#     subkey_type: ""
#     subkey_length: < length >
#     expiry: ""
#     passphrase: ""
#
#   git:
#     enabled: < true | false >
#     fetch_keys: < true | false >
#     key_source: ""
#     key_id: ""
#     signing_key: ""
#
#  smtp:
#     accounts:
#       - name: ""
#         enabled: < true | false >
#         account_name: ""
#         username: ""
#         password: ""
#         hostname: ""
#         port: < port >
#         use_tls: < true | false >
#
#   systemd:
#     enabled: < true | false >
#     services:
#      - name: "service.<service | target | timer >"
