# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
- name: Send a notification email
  community.general.mail:
    body: "{{ message_body }}"
    host: "{{ send_notification_.smtp.host | defaults.smtp.host }}"
    port: "{{ defaults.smtp.port }}"
    username: "{{ defaults.smtp.username }}"
    password: "{{ defaults.smtp.password }}"
    sender: "{{ defaults.smtp.username }}"
    subject: "{{ message_subject }}"
    to: "{{ message_to }}"
  delegate_to: localhost
  listen: send-notification
