---
services:
  postgres:
    image: postgres:latest
    pull_policy: missing
    restart: unless-stopped
    hostname: "postgres.svc.caspersbox.com"
    container_name: "postgres"
    networks:
      service-network:
        ipv4_address: 192.168.1.13
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres
    secrets:
      - source: postgres
        target: /run/secrets/postgres
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:latest
    pull_policy: missing
    restart: unless-stopped
    hostname: "keycloak.svc.caspersbox.com"
    container_name: "keycloak"
    networks:
      service-network:
        ipv4_address: 192.168.1.14
    ports:
      - 9080:9080
    env_file:
      - path: ./.env
        required: true
    environment:
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://192.168.1.13:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "${KC_DB_PASSWORD}"
      KC_HOSTNAME: "localhost"
      KC_HTTP_PORT: 9080
      KC_HOSTNAME_STRICT: false
      KC_LOG_LEVEL: "info"
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KC_BOOTSTRAP_ADMIN_PASSWORD}"
      KC_ADMIN: "admin"
      KC_ADMIN_PASSWORD: "${KC_ADMIN_PASSWORD}"
    command: "${KC_START_COMMAND}"

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/postgres/data"

---
networks:
  service-network:
    external: true

---
secrets:
  postgres:
    file: "~/workspace/keycloak/postgres.txt"
