# =====  ANSIBLE  ============================================================
#          NAME:  roles/ansible/send_notification/tasks/main.yml
#   DESCRIPTION:  Primary entry point for this play
# ============================================================================
---
- name: Send alert notification
  ansible.builtin.debug:
    msg: "A notification message is being sent"
  notify:
    - send-notification
