# =====  ANSIBLE  ============================================================
#          NAME:  site.yml
#   DESCRIPTION:  Entry point for playbook
# ============================================================================
---
send_notification:
  smtp:
    hostname: "smtp.google.com"
    port: 587
