# ====  ANSIBLE   =============================================================
#          NAME:  roles/common/tasks/main.yml
#   DESCRIPTION:  Main entry point for common tasks
# =============================================================================
---
- name: Include default variables
  ansible.builtin.include_vars:
    file: "vars/main.yml"

- name: Main custom role running subtask(s)
  ansible.builtin.include_tasks:
    file: "{{ ansible_setup_item }}"
  loop:
    - setup-ansible.yml
  loop_control:
    loop_var: "ansible_setup_item"
