# ====  ANSIBLE   =============================================================
#          NAME:  roles/ansible/tasks/setup-ansible.yml
#   DESCRIPTION:  Main entry point for common tasks
# =============================================================================
---
- name: Create and set up Ansible workspace
  ansible.builtin.debug:
    msg: "Installing Ansible workspace"
  notify:
    - create-ansible-workspace
    - install-ansible-workspace
