# ====  ANSIBLE   =============================================================
#          NAME:  roles/common/handlers/main.yml
#   DESCRIPTION:  Main entry point for common tasks
# =============================================================================
---
- name: Activate new Python virtual environment
  ansible.builtin.command:
    cmd: "{{ user_account.home_dir | default(ansible_user_dir) }}/workspace/venv/activate"
  changed_when: true
  listen: activate-python-venv
