---
services:
  bind9:
    image: internetsystemsconsortium/bind9:9.21
    restart: on-failure
    container_name: bind9-dns
    ports:
      - "10953:53/udp"
      - "10953:53/tcp"
    volumes:
      - config:/etc/bind
      - namedb:/var/lib/bind
    # healthcheck:
    #   test: ["CMD", "dig", "@", "localhost", "+short", "-t", "a", "localhost.localdomain"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

---
volumes:
  namedb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/namedb"
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/etc"
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/logs"
