# =====  ANSIBLE  ============================================================
#          NAME:  requirements.yml
#   DESCRIPTION:  It's for the linter
# ============================================================================
---
dependencies:
- role: send-notification
