# ====  ANSIBLE   =============================================================
#          NAME:  group_vars/all/main.yml
#   DESCRIPTION:  Common variables that apply to this play
# =============================================================================
---
setup_ansible_:
  smtp:
    host: "localhost"
    port: 25
