---
services:
  akhq:
    image: tchiotludo/akhq:latest
    restart: unless-stopped
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8080:8080
    links:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data:Z
      - zookeeper-log:/var/lib/zookeeper/log:Z
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    volumes:
      - kafka-data:/var/lib/kafka/data:Z
    environment:
      CLUSTER_ID: "fzR8_urgTSCZgFdIBSwJOg"
      KAFKA_CLUSTER_ID: "fzR8_urgTSCZgFdIBSwJOg"
      KAFKA_BROKER_ID: '0'
      KAFKA_KRAFT_MODE: "true"               
      KAFKA_NODE_ID: '0'
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_NUM_PARTITIONS: '12'
      KAFKA_COMPRESSION_TYPE: 'gzip'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: '9091'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
    links:
      - zookeeper

---
volumes:
  zookeeper-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/Apache/kafka/zookeeper/data"

  zookeeper-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/Apache/kafka/zookeeper/logs"

  kafka-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/Apache/kafka/kafka/data"

