---
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    pull_policy: missing
    restart: unless-stopped
    hostname: zookeeper
    container_name: zookeeper
    networks:
      service-network:
        ipv4_address: 192.168.1.6
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data:Z
      - zookeeper-log:/var/lib/zookeeper/log:Z
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    pull_policy: missing
    restart: unless-stopped
    hostname: kafka
    container_name: kafka
    networks:
      service-network:
        ipv4_address: 192.168.1.7
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data:Z
    environment:
      CLUSTER_ID: "fzR8_urgTSCZgFdIBSwJOg"
      KAFKA_CLUSTER_ID: "fzR8_urgTSCZgFdIBSwJOg"
      KAFKA_BROKER_ID: '0'
      KAFKA_KRAFT_MODE: "true"               
      KAFKA_NODE_ID: '0'
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,EXTERNAL://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_NUM_PARTITIONS: '12'
      KAFKA_COMPRESSION_TYPE: 'gzip'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: '9091'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
    links:
      - zookeeper
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:latest
    pull_policy: missing
    restart: unless-stopped
    hostname: akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    networks:
      service-network:
        ipv4_address: 192.168.1.8
    ports:
      - 8080:8080
    links:
      - kafka
    depends_on:
      - zookeeper
      - kafka

  connect:
    image: confluentinc/cp-kafka-connect:7.7.7
    pull_policy: missing
    hostname: connect
    container_name: connect
    networks:
      service-network:
        ipv4_address: 192.168.1.9
    ports:
      - "8083:8083"
    environment:
      # Connect to the Kafka broker internally via its service name and internal port
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      # Set the plugin path to include default directories
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
    links:
      - kafka
    depends_on:
      - kafka

---
volumes:
  zookeeper-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/Apache/kafka/zookeeper/data"

  zookeeper-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/Apache/kafka/zookeeper/logs"

  kafka-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/Apache/kafka/kafka/data"

---
networks:
  service-network:
    external: true

