# =====  ANSIBLE  ============================================================
#          NAME:  roles/dotfiles/tasks/create-config-links.yml
#   DESCRIPTION:  Primary entry point for this play
# ============================================================================
---
- name: "Remove any existing configuration directories (${HOME}/.config)"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/{{ rm_config_item }}"
    state: "absent"
  loop:
    - "environment.d"
    - "git"
    - "systemd"
    - "tmux"
  loop_control:
    loop_var: "rm_config_item"

- name: "Create links for ${HOME}/.config"
  ansible.builtin.file:
    src: "{{ install.base_path }}/config/{{ ln_config_item }}"
    dest: "{{ ansible_user_dir }}/.config/{{ ln_config_item }}"
    state: "link"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - "environment.d"
    - "git"
    - "systemd"
    - "tmux"
  loop_control:
    loop_var: "ln_config_item"
