# =====  ANSIBLE  ============================================================
#          NAME:  roles/dotfiles/tasks/handle-ssh-keys.yml
#   DESCRIPTION:  Primary entry point for this play
# ============================================================================
---
- name: "Create or update permissions on ${HOME}/.ssh"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0700"

- name: "Remove any existing configuration entries (${HOME}/.ssh)"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/{{ rm_ssh_config_item }}"
    state: "absent"
  loop:
    - "config"
    - "config.d"
  loop_control:
    loop_var: "rm_ssh_config_item"

- name: "Create links in ${HOME}/.ssh"
  ansible.builtin.file:
    src: "{{ install.base_path }}/config/ssh/{{ ssh_item }}"
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_item }}"
    state: "link"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - "config"
    - "config.d"
  loop_control:
    loop_var: "ssh_item"

- name: "Create ${HOME}/.ssh/local.d"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/local.d"
    state: "directory"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0755"

- name: "Create SSH private key (if provided)"
  ansible.builtin.copy:
    content: "{{ user_account.ssh.key_data }}"
    dest: "{{ ansible_user_dir }}/.ssh/id_{{ user_account.ssh.key_type }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  when:
    - user_account.ssh.generate_keys is false
    - user_account.ssh.fetch_keys is false
    - user_account.ssh.key_data is defined
    - user_account.ssh.key_data | length > 0

- name: "Create SSH key (if enabled, with passphrase)"
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_{{ user_account.ssh.key_type }}"
    type: "{{ user_account.ssh.key_type }}"
    comment: ""
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
    passphrase: "{{ user_account.ssh.passphrase }}"
  when:
    - user_account.ssh.fetch_keys is false
    - user_account.ssh.passphrase is defined

- name: "Create SSH key (if enabled, no passphrase)"
  community.crypto.openssh_keypair:
    path: "{{ ansible_user_dir }}/.ssh/id_{{ user_account.ssh.key_type }}"
    type: "{{ user_account.ssh.key_type }}"
    comment: ""
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  when:
    - user_account.ssh.fetch_keys is false
    - user_account.ssh.passphrase is undefined

- name: "Save service account file (Google Cloud)"
  ansible.builtin.copy:
    content: "{{ secrets.google.GCP_SERVICE_ACCOUNT }}"
    dest: "{{ install.tmp_dir | default(ansible_user_dir) }}/service_account.json"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  when:
    - user_account.ssh.fetch_keys is true
    - user_account.ssh.key_source == "gcloud"
    - secrets.google.GCP_SERVICE_ACCOUNT is defined
    - secrets.google.GCP_SERVICE_ACCOUNT | length > 0

- name: "Get SSH key (Google Cloud)"
  vars:
    auth_kind: "serviceaccount"
    service_account_file: "{{ install.tmp_dir | default(ansible_user_dir) }}/service_account.json"
    project: "{{ gcp.projects.project_id }}"
    secret_id: "{{ user_account.ssh.key_id }}"
    dotfiles_ssh_private_key_output: "{{ lookup('google.cloud.gcp_secret_manager', project=project, auth_kind=auth_kind, service_service_account_file=service_account_file, key=secret_id) }}"
  ansible.builtin.debug:
    msg: "Fetching key from Google Cloud"
  when:
    - user_account.ssh.fetch_keys is true
    - user_account.ssh.key_source == "gcloud"
    - secrets.google.GCP_SERVICE_ACCOUNT is defined
    - secrets.google.GCP_SERVICE_ACCOUNT | length > 0
    - gcp.projects.project_id is defined
    - gcp.projects.project_id | length > 0

- name: "Save fetched SSH key file"
  ansible.builtin.copy:
    content: "{{ dotfiles_ssh_private_key_output }}"
    dest: "{{ ansible_user_dir }}/.ssh/id_{{ user_account.ssh.key_type }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  when:
    - user_account.ssh.fetch_keys is true

- name: "Remove service account file"
  ansible.builtin.file:
    path: "{{ install.tmp_dir | default(ansible_user_dir) }}/service_account.json"
    state: absent
  when:
    - user_account.ssh.fetch_keys is true
    - secrets.google.GCP_SERVICE_ACCOUNT is defined
    - secrets.google.GCP_SERVICE_ACCOUNT | length > 0
