profile: production
strict: true
use_default_rules: true
quiet: true
verbosity: 1
skip_action_validation: false

skip_list:
  - var-naming[no-role-prefix]

enable_list:
  - args
  - empty-string-compare
  - no-log-password
  - no-same-owner
  - name
  - yaml
  - jinja

rules:
  line-length: disable
