profile: production
strict: true
use_default_rules: true

skip_list:
  - '403'
  - 'role-name'

enable_list:
  - args
  - empty-string-compare
  - no-log-password
  - no-same-owner
  - name
  - yaml
  - jinja
