# =====  ANSIBLE  ============================================================
#          NAME:  requirements.yml
#   DESCRIPTION:  It's for the linter
# ============================================================================
---
collections:
  - ansible.posix
  - community.crypto
  - google.cloud
