# =====  ANSIBLE  ============================================================
#          NAME:  tasks/deploy-files.yml
#   DESCRIPTION:  Primary entry point for this play
# =============================================================================
---
- name: Create SSH key pair (if enabled, with passphrase)
  community.crypto.openssh_keypair:
    path: "{{ user_account.home_dir | default(ansible_user_dir) }}/.ssh/id_{{ user_account.ssh.key_type }}"
    type: "{{ user_account.ssh.key_type }}"
    comment: ""
    mode: "0600"
    passphrase: "{{ user_account.ssh.passphrase }}"
  when:
    - user_account.ssh.ssh_passphrase is defined
    - not install_dotfiles_key_exists.stat.exists
  listen: create-ssh-key-with-passphrase

- name: Create SSH key pair (if enabled, no passphrase)
  community.crypto.openssh_keypair:
    path: "{{ user_account.home_dir | default(ansible_user_dir) }}/.ssh/id_{{ user_account.ssh.key_type }}"
    type: "{{ user_account.ssh.key_type }}"
    comment: ""
    mode: "0600"
  when:
    - user_account.ssh.ssh_passphrase is undefined
    - not install_dotfiles_key_exists.stat.exists
  listen: create-ssh-key-with-passphrase
