# ====  ANSIBLE   =============================================================
#          NAME:  group_vars/all/main.yml
#   DESCRIPTION:  Common variables that apply to this play
# =============================================================================
---
- name: Save GPG private key file
  ansible.builtin.copy:
    content: "{{ install_dotfiles_gpg_private_key_output.value }}"
    dest: "{{ user_account.home_dir }}/.config/gnupg/privkey.asc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
  listen: save-gpg-key
