---
services:
  bind:
    image: internetsystemsconsortium/bind9:9.20
    pull_policy: missing
    restart: unless-stopped
    hostname: "ns1.caspersbox.local"
    container_name: "isc-bind9-ns1"
    networks:
      service-network:
        ipv4_address: 192.168.1.5
    ports:
      - "10953:53/udp"
      - "10953:53/tcp"
    environment:
      TZ: "EDT"
    volumes:
      - dns-config:/etc/bind:rw
      - dns-master-zones:/var/cache/bind:rw
      - dns-slave-zones:/var/lib/bind:rw
      - dns-log:/var/log/bind:rw
    healthcheck:
      test: ["CMD", "dig", "@localhost", "+short", "-t", "a", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

---
volumes:
  dns-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/etc"

  dns-master-zones:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/namedb"

  dns-slave-zones:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/cache"

  dns-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/named/log"

---
networks:
  service-network:
    external: true
