# =====  WORKFLOW  ============================================================
#          NAME:  ansible-linter.yml
#   DESCRIPTION:  GitHub action for yaml linter
# ============================================================================
name: yaml linter - Ansible Playbook
on: [push, pull_request]

jobs:
  lint:
    name: Run yaml linter on Ansible playbooks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Bitwarden SDK
        run: |
          pip install bitwarden-sdk

      - name: Run Ansible linter on playbooks
        uses: ansible/ansible-lint@main
        with:
          args: ""
          setup_python: "true"
          working_directory: "ansible"
          requirements_file: ""
